fix(config): use static IPs for core services
todanni/orchestrate pull request #7
Opened 2021-05-12 16:45 UTC by stegzilla

2021-05-12 19:42 UTC, danni-popova approved these changes

2021-05-12 19:43 UTC, danni-popova requested changes

2021-05-12 19:43 UTC, danni-popova commented on dev-docker-compose.yml
> -      - RABBITMQ_DEFAULT_PASS=docker
give them backl

2021-05-12 19:45 UTC, stegzilla commented on dev-docker-compose.yml
> -      - RABBITMQ_DEFAULT_PASS=docker
it is done

2021-05-13 09:44 UTC, danni-popova approved these changes

2021-05-13 09:45 UTC, merged